// Copyright 2020 Paingha Joe Alagoa. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"github.com/jinzhu/gorm"
	"github.com/paingha/winkel/api/config"
	"github.com/paingha/winkel/api/models"
	"github.com/paingha/winkel/api/plugins"
	"github.com/paingha/winkel/api/routes"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/paingha/winkel/api/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Winkel Ecommerce Store API
// @version 1.0
// @description This is an api server for an online store.
// @termsOfService https://www.iamjollof.com/open-source/winkel/license

// @contact.name Paingha Joe Alagoa
// @contact.url https://www.iamjollof.com/open-source/winkel
// @contact.email apaingha@gmail.com
// @schemes http https
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /v1
var err error

func main() {
	//system config
	systemCfg := &config.SystemConfig{}
	if err := config.InitConfig(systemCfg); err != nil {
		plugins.LogFatal("API", "Wrong config", err)
	}
	// Connect to Database
	config.DB, err = gorm.Open("postgres", config.GetConnectionContext())
	if err != nil {
		plugins.LogFatal("API", "Database connection error", err)
	}
	defer config.DB.Close()
	config.DB.LogMode(true)
	config.DB.AutoMigrate(&models.User{})
	config.DB.AutoMigrate(&models.Categories{})
	config.DB.AutoMigrate(&models.Subcategories{})
	localServer := ":8080"
	//setup routes
	r := routes.SetupRouter()
	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))
	// running
	if err := r.Run(localServer); err != nil {
		plugins.LogFatal("API", "An Error occured while starting the server", err)
	}
}
