
set ENV_PROD_DB_HOST=localhost
set ENV_PROD_DB_PORT=5432
set ENV_PROD_DB_USER=postgres
set ENV_PROD_DB_PASS=123456
set ENV_PROD_DB_DATABASE=winkel
set ENV_PROD_DB_SSL=disable
set ENV_DEV_DB_HOST=localhost
set ENV_DEV_DB_PORT=5432
set ENV_DEV_DB_USER=postgres
set ENV_DEV_DB_PASS=123456
set ENV_DEV_DB_DATABASE=winkel
set ENV_DEV_DB_SSL=disable
set JWT_SECRET=A_RANDOM_STRING_TO_BE_USED_TO_SIGN_JWT_TOKENS
set ENV_SENDGRID_API_KEY=YOUR_SENDGRID_API_KEY_GOES_HERE
set ENV_SENDER_EMAIL=YOUR_SENDGRID_SENDER_EMAIL_GOES_HERE
set ENV_BASE_URL=YOUR_BASE_DOMAIN_NAME_GOES_HERE (http://localhost:8080/v1)
go mod vendor
go build
api.exe

pause